entities/urls.py
# youbee_main/entities/urls.py

# System libraries

# Third-party libraries

# Django modules
from django.urls import path

# Django apps

#  Current app modules
from .views import (EntityDetailView,
                    CreateDepartmentView,
                    UpdateDepartmentView,
                    DeleteDepartmentView,
                    CreateEmployeeView,
                    DepartmentTableView,
                    EmployeeTableView,
                    UpdateEmployeeView,
                    DeleteEmployeeView,
                    )

app_name = 'entities'

urlpatterns = [
    path('detail/', EntityDetailView.as_view(), name='entity_detail'),
    path('departments/', DepartmentTableView.as_view(), name='entity_departments'),
    path('departments/create', CreateDepartmentView.as_view(), name='create_department'),
    path('departments/<int:pk>/update', UpdateDepartmentView.as_view(), name='update_department'),
    path('departments/<int:pk>/delete', DeleteDepartmentView.as_view(), name='delete_department'),
    path('employees/', EmployeeTableView.as_view(), name='entity_employees'),
    path('employees/create', CreateEmployeeView.as_view(), name='create_employee'),
    path('employees/<int:pk>/update', UpdateEmployeeView.as_view(), name='update_employee'),
    path('employees/<int:pk>/delete', DeleteEmployeeView.as_view(), name='delete_employee'),
]

home/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView, ContactPageView, DashboardPageView

# app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('dashboard/', DashboardPageView.as_view(), name='dashboard'),
]

users/urls.py
from django.urls import path, re_path

from .views import RegisterView, SigninView, SignoutView, MyPasswordResetView, MyPasswordResetDoneView, \
    MyPasswordResetFromKeyView,MyPasswordResetFromKeyDoneView, MyPasswordChangeView, UserDetailView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', SigninView.as_view(), name='signin'),
    path('logout/', SignoutView.as_view(), name='signout'),
    path('password/change/', MyPasswordChangeView.as_view(), name='password_change'),
    path('password/reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", MyPasswordResetFromKeyView.as_view(),
            name="reset_password_from_key", ),
    path("password/reset/key/done/", MyPasswordResetFromKeyDoneView.as_view(), name="reset_password_from_key_done", ),
    path('user/detail/', UserDetailView.as_view(), name='user_detail'),
    ]

youbee_main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('entity/', include('entities.urls')),
]

templates/includes/_anonymous_menu.html
<a href="{% url 'users:register' %}">
    <div class="lcars-element button">Register</div>
</a>
<a href="{% url 'users:signin' %}">
    <div class="lcars-element button">Sign in</div>
</a>

templates/includes/_logged_menu.html
{% if user.employee.is_manager %}
<a href="{% url 'dashboard' %}">
    <div class="lcars-element button lcars-sandy-brown-bg">Dashboard</div>
</a>
<a href="{% url 'entities:entity_detail' %}">
    <div class="lcars-element button lcars-sandy-brown-bg">Entity Details</div>
</a>
<a href="{% url 'entities:entity_departments' %}">
    <div class="lcars-element button lcars-sandy-brown-bg">Departments</div>
</a>
<a href="{% url 'entities:entity_employees' %}">
    <div class="lcars-element button lcars-sandy-brown-bg">Employees</div>
</a>
{% endif %}
{% if user.is_entity_supervisor %}
<a href="#">
    <div class="lcars-element button lcars-sandy-brown-bg">Partners</div>
</a>
{% endif %}