entities/urls.py
# youbee_main/entities/urls.py

# System libraries

# Third-party libraries

# Django modules
from django.urls import path

# Django apps

#  Current app modules
from .views import (EntityDetailView,
                    CreateDepartmentView,
                    UpdateDepartmentView,
                    DeleteDepartmentView,
                    CreateEmployeeView,
                    DepartmentTableView,
                    EmployeeTableView,
                    UpdateEmployeeView,
                    DeleteEmployeeView,
                    )

app_name = 'entities'

urlpatterns = [
    path('detail/', EntityDetailView.as_view(), name='entity_detail'),
    path('departments/', DepartmentTableView.as_view(), name='entity_departments'),
    path('departments/create', CreateDepartmentView.as_view(), name='create_department'),
    path('departments/<int:pk>/update', UpdateDepartmentView.as_view(), name='update_department'),
    path('departments/<int:pk>/delete', DeleteDepartmentView.as_view(), name='delete_department'),
    path('employees/', EmployeeTableView.as_view(), name='entity_employees'),
    path('employees/create', CreateEmployeeView.as_view(), name='create_employee'),
    path('employees/<int:pk>/update', UpdateEmployeeView.as_view(), name='update_employee'),
    path('employees/<int:pk>/delete', DeleteEmployeeView.as_view(), name='delete_employee'),
]

entities/models.py
# youbee_main/entities/models.py

# System libraries
from enum import Enum

# Third-party libraries
from model_utils.fields import StatusField, MonitorField
from model_utils import Choices
from autoslug import AutoSlugField
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField

# Django modules
from django.db import models
from django.urls import reverse

# Django apps
from users.models import User

#  Current app modules


def _employee_slug_fields(instance):
    return "{0}-{1}".format(instance.user.first_name, instance.user.last_name)


class Entity(models.Model):
    class Meta:
        verbose_name_plural = 'entities'
        constraints = [models.UniqueConstraint(fields=['name'], name='unique_entity_name')]
        ordering = ['name']

    name = models.CharField(max_length=48,
                            verbose_name='Name',
                            unique=True,
                            help_text='Name of the entity you are working for. Please make sure it is correct')
    slug_name = AutoSlugField(populate_from='name',
                              verbose_name='Slug',
                              max_length=54,
                              unique=True,
                              editable=False)
    supervisor = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    parent = models.ForeignKey('self', on_delete=models.PROTECT, blank=True, null=True, related_name='partners')

    def __str__(self):
        return "{name}".format(name=self.name)

    @property
    def get_absolute_url(self):
        return reverse('entities:entity_detail')


class EntityDetail(models.Model):
    class Meta:
        verbose_name_plural = 'entity_details'

    entity = models.OneToOneField(Entity,
                                  on_delete=models.CASCADE,
                                  related_name='entity_details')

    phone1 = PhoneNumberField(blank=True,
                              verbose_name='Phone1',
                              help_text="Enter a phone number")
    phone2 = PhoneNumberField(blank=True,
                              verbose_name='Phone2',
                              help_text="Enter a phone number")

    email1 = models.EmailField(max_length=48,
                               verbose_name='Email1',
                               blank=True,
                               help_text="Enter an email address")
    email1_checked = models.BooleanField(default=False, editable=False)
    email2 = models.EmailField(max_length=48,
                               verbose_name = 'Email2',
                               blank=True,
                               help_text="Enter an email address")
    email2_checked = models.BooleanField(default=False, editable=False)

    address1 = models.CharField(max_length=128,
                                verbose_name='Address1',
                                blank=True,
                                help_text="Enter an address")
    address2 = models.CharField(max_length=128,
                                verbose_name='Address2',
                                blank=True,
                                help_text="Enter an address")
    city = models.CharField(max_length=32,
                            verbose_name='City',
                            blank=True,
                            help_text="Enter a city")
    country = CountryField(blank_label='(select country)',
                           verbose_name='Country',
                           blank=True)
    zip_code = models.CharField(max_length=16,
                                verbose_name='Zip Code',
                                blank=True,
                                help_text="Enter a zip code")

    def __str__(self):
        return "{name} - [phone: {phone} email: {email}]".format(
            name=self.entity.name, phone=self.phone1,
            email=self.email1)

    @property
    def get_values(self):
        return {'entity': self.entity,
                'name': self.entity.name,
                'address1': self.address1,
                'address2': self.address2,
                'city': self.city,
                'country': self.country,
                'zip_code': self.zip_code,
                'email1': self.email1,
                'email2': self.email2,
                'phone1': self.phone1,
                'phone2': self.phone2,
                }

    @property
    def get_absolute_url(self):
        return reverse('entities:entity_detail')


class Department(models.Model):
    class Meta:
        permissions = [('unlink_department', 'Can unlink department'), ]
        unique_together = [['entity', 'name'], ]
        ordering = ['entity', 'name']

    name = models.CharField(max_length=24,
                            verbose_name='Name',
                            help_text='Enter a department name')
    entity = models.ForeignKey(Entity,
                               on_delete=models.CASCADE,
                               related_name='departments')

    @property
    def get_values(self):
        return {
            'name': self.name,
            'entity': self.entity,
        }

    def __str__(self):
        return self.name

    @property
    def employee_count(self):
        return self.employees.count()


class Employee(models.Model):
    class Meta:
        permissions = [('unlink_employee', 'Can unlink employee'), ]
        ordering = ['user__last_name', 'user__first_name']

    class GENDERS(Enum):
        male = ('M', 'Male')
        female = ('F', 'Female')
        undefined = ('U', 'Undefined')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    class TITLES(Enum):
        mr = ('1', 'Mr')
        mrs = ('2', 'Mrs')
        ms = ('3', 'Ms')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    STATUS = Choices('not sent', 'initiated', 'sent',
                     'confirmed OK', 'confirmed not OK')

    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    slug_name = AutoSlugField(
        populate_from=_employee_slug_fields,
        max_length=200,
        unique=True,
        editable=False)
    title = models.CharField(max_length=1,
                             default='1',
                             choices=[x.value for x in TITLES],
                             help_text='Select a title in the list.')
    gender = models.CharField(max_length=1,
                              default='U',
                              choices=[x.value for x in GENDERS])

    email2 = models.EmailField(max_length=48,
                               blank=True)
    phone1 = PhoneNumberField(blank=True)
    phone2 = PhoneNumberField(blank=True)
    whatsapp = PhoneNumberField(blank=True,
                                help_text='Enter a whatsapp number')
    twitter = models.CharField(max_length=15,
                               blank=True,
                               help_text='Enter a Twitter account')
    # Status data
    status = StatusField(default='not sent',
                         choices_name='STATUS', editable=False)
    status_changed = MonitorField(monitor='status', editable=False)
    initiated_on = MonitorField(monitor='status', when=[
        'initiated'], editable=False)
    sent_on = MonitorField(monitor='status', when=['sent'], editable=False)
    confirmed_on = MonitorField(monitor='status', when=[
        'confirmed OK', 'confirmed not OK'], editable=False)

    entity = models.ForeignKey(
        Entity, on_delete=models.CASCADE, editable=False, related_name='employees')
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, editable=False, related_name='employees')
    is_manager = models.BooleanField(default=False, editable=False)

    @property
    def full_name(self):
        return self.__str__()

    def save(self, *args, **kwargs):
        self.gender = 'M' if self.title == '1' else 'F'
        self.is_manager = (self.user.is_entity_supervisor or self.user.is_entity_manager)
        super().save(*args, **kwargs)
        return self

    def __str__(self):
        return "{first_name} {last_name}".format(first_name=self.user.first_name, last_name=self.user.last_name)


class Partnership(models.Model):
    class Meta:
        verbose_name_plural = 'partnerships'

    STATUS = Choices('not sent', 'sent', 'OK', 'NOK')

    entity = models.ForeignKey(Entity, on_delete=models.CASCADE)

    # Status data
    status = StatusField(default='not sent',
                         choices_name='STATUS',
                         editable=False)
    status_changed = MonitorField(monitor='status',
                                  editable=False)
    sent_on = MonitorField(monitor='status',
                           when=['sent'],
                           editable=False)
    confirmed_on = MonitorField(monitor='status',
                                when=['OK', 'NOK'],
                                editable=False)
    validity_start = models.DateField()
    validity_end = models.DateField()

entities/templates/entities/department_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/department_confirm_delete.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">DELETE DEPARTMENT</div>
        <div class="lcars-u-8-3" style="margin-left: 40px;">
            <form id="delete_department_form"
                  action="{% url 'entities:delete_department' department.pk %}"
                  method="POST">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete the department: <b>{{ department }}</b>
                </p>
                <div class="lcars-row centered button-row">
                    <div class="lcars-column lcars-u-2">
                        <div class="button-grid">
                            <button class="lcars-element button uppercase lcars-husk-bg"
                                    type="submit">Confirm
                            </button>
                            <a id="cancel_department_delete" href="{% url 'entities:entity_departments' %}">
                                <button class="lcars-element button uppercase lcars-red-damask-bg"
                                        type="button">Cancel
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

entities/templates/entities/department_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/department_form.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8 lcars-black-bg">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">NEW DEPARTMENT</div>
        <div class="lcars-u-8-4" style="margin-left: 40px;">
            <form id="department_form"
                  action="{% url 'entities:create_department' %}"
                  method="POST">
                {% csrf_token %}
                <br>
                <p> <!-- Department name input -->
                    <label for="name"
                           class="lcars-u-1 uppercase"
                           title="Required. Enter the department name"
                           style="display: inline-block;">
                        <b>{{ form.name.label}} </b>
                    </label>
                    <input class="lcars-u-6 decorated rounded lcars-golden-tanoi-color"
                           id="name"
                           name="name"
                           type="text"
                           title="Required. Enter the department name"
                           placeholder="Enter the department name"
                           maxlength="24"
                           required
                           autofocus>
                </p>
                </p>
                {% include './includes/_form_buttons_department.html' %}
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

entities/templates/entities/department_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/department_list.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-column lcars-u-4">
        <div style="display: block;">
            <div style="margin-bottom: 1rem;">
                <a class="" style="" href="{% url 'entities:create_department' %}" title="Click to add a department">
                    <i class="fas fa-plus-square"></i> Add Department</a>
            </div>
            <table class="lcars-table lcars-golden-tanoi-color special-caption">
                <caption>DEPARTMENTS</caption>
                <th>Name</th>
                <th>Employees</th>
                <th>Actions</th>
                {% for d in department_list %}
                <tr class="{% cycle 'lcars-black-bg' 'lcars-mariner-bg' %} lcars-golden-tanoi-color">
                    <td>{{ d.name }}</td>
                    <td>{{ d.employee_set.all.count }}</td>
                    <td>
                        <a class="icon" href="{% url 'entities:update_department' d.pk %}" title="Click to update the department name"><i class="fas fa-pen"></i></a>
                        <span class="">
                        <a class="icon" href="{% url 'entities:delete_department' d.pk %}" title="Click to delete a department"><i class="fas fa-eraser"></i></a>
                        </span>
                        <span class="">
                        <a class="icon" href="" title="Click to link/unlink a department"><i class="fas fa-link"></i></a>
                        </span>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

entities/templates/entities/employee_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/employee_list.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-u-8">
        <div class="table-container">
            <div class="first-row-container">
                <a class=""
                   href="{% url 'entities:create_employee' %}"
                   title="Click to add an employee">
                    <i class="fas fa-plus-square"></i> Add Employee
                </a>
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                    </span>
                </div>
            </div>
            <table class="lcars-table lcars-golden-tanoi-color special-caption">
                <caption>EMPLOYEES</caption>
                <tbody>
                <tr>
                    <th></th>
                    <th>Full name</th>
                    <th></th>
                    <th>Department</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Actions</th>
                </tr>
                {% for e in employee_list %}
                <tr class="{% cycle 'lcars-black-bg' 'lcars-mariner-bg' %} lcars-golden-tanoi-color">
                    <td class="data_cell">{{ e.get_title_display }}</td>
                    <td>{{ e.user.first_name }}</td>
                    <td>{{ e.user.last_name }}</td>
                    <td class="data_cell">{{ e.department.name }}</td>
                    <td class="data_cell">{{ e.user.email }}</td>
                    <td class="data_cell">
                        <select class="lcars-select {% cycle 'lcars-black-bg' 'lcars-mariner-bg' %} lcars-golden-tanoi-color">
                            {% for role in e.user.get_roles_names %}
                            <option>{{ role }}</option>
                            {% empty %}
                            <option>No Role</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td class="data_cell {% cycle 'lcars-black-bg lcars-golden-tanoi-color' 'lcars-mariner-bg lcars-black-color' %}">
                        <a class=" icon" href="" title="Click to update the employee data"><i
                                class="fas fa-pen"></i></a>
                        <span class="">
                        <a class="icon" href="" title="Click to delete the employee"><i class="fas fa-eraser"></i></a>
                        </span>
                        <span class="">
                        <a class="icon" href="" title="Click to link/unlink the employee"><i
                                class="fas fa-link"></i></a>
                        </span>
                    </td>
                </tr>
                {% empty %}
                    No employee yet
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

entities/templates/entities/employee_update_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/employee_update_form.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">UPDATE EMPLOYEE</div>
        <div class="lcars-u-8-6">
            <form id="employee_update_form"
                  action="{% url 'entities:update_employee' employee.pk %}?next={% url 'entities:entity_employees' %}"
                  method="POST">
                {% csrf_token %}
                <div class="lcars-form">
                    <div class="lcars-form-row"> <!--first_name and last name-->
                        <div class="lcars-form-field">
                            <div class="title">
                                <label for="first_name"
                                       title=""
                                       class="">
                                    <b>{{ form.first_name.label }}</b>
                                </label>
                                <span class="lcars-u-1" style="margin-left: 6px;">
                            <select class="lcars-black-bg lcars-white-color"
                                    id="title"
                                    name="title"
                                    title="Required. Choose a title from the list"
                                    required>
                                <option value="1" {% if form.title.value == '1' %}selected{% endif %}>Mr.</option>
                                <option value="2" {% if form.title.value == '2' %}selected{% endif %}>Mrs.</option>
                                <option value="3" {% if form.title.value == '3' %}selected{% endif %}>Ms.</option>
                            </select>
                            </span>
                            </div>
                            <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                                   style="width: 15.85rem;"
                                   id="first_name"
                                   name="first_name"
                                   type="text"
                                   value="{{ employee.user.first_name }}"
                                   title=""
                                   placeholder="Enter the first name of the new employee"
                                   maxlength="150"
                                   disabled/>
                        </div>
                        <div class="lcars-form-field">
                            <label for="last_name"
                                   title=""
                                   class="lcars-u-1 uppercase">
                                <b>{{ form.last_name.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="last_name"
                                   name="last_name"
                                   type="text"
                                   value="{{ employee.user.last_name }}"
                                   title=""
                                   placeholder="Enter the last name of the new employee"
                                   maxlength="150"
                                   disabled/>

                        </div>
                    </div> <!--  lcars-form-row -->
                    <div class="lcars-form-row"> <!-- password and role -->
                        <div class="lcars-form-field">
                            <label for="password"
                                   class="lcars-u-1 uppercase"
                                   style="margin-right: 10px;">
                                <b>{{ form.password.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   name="password"
                                   type="password"
                                   title="Enter the new password"
                                   placeholder="Enter a password"
                                   id="password"
                                   maxlength="128"
                                   autofocus>
                        </div>
                        <div class="lcars-form-field">
                            <label for="role"
                                   class="lcars-u-1 uppercase">
                                <b>{{ form.role.label }}</b>
                            </label>
                            <select class="lcars-select lcars-black-bg lcars-golden-tanoi-color"
                                    id="role"
                                    title=""
                                    name="role"
                                    required>
                                {% for r in role_list %}
                                    <option value="{{ r.pk }}" {% if r in employee.user.get_roles %}selected{% endif %}>{{ r.name }}</option>
                                {% endfor role_list %}
                            </select>
                        </div>
                    </div> <!--  lcars-form-row -->
                    <div class="lcars-form-row">
                        <div class="lcars-form-field">
                            <label for="email1"
                                   class="lcars-u-1 uppercase"
                                   title=""
                                   style="margin-right: 10px;">
                                <b>{{ form.email1.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="email1"
                                   name="email1"
                                   type="email"
                                   title=""
                                   value="{{ employee.user.email }}"
                                   placeholder="Enter the email address"
                                   maxlength="48"
                                   disabled />
                        </div>
                        <div class="lcars-form-field">
                            <label for="email2"
                                   class="lcars-u-1 uppercase">
                                <b>{{ form.email2.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="email2"
                                   name="email2"
                                   title=""
                                   value="{{ form.email2.value }}"
                                   type="email"
                                   placeholder="Enter the email address"
                                   maxlength="48"/>
                        </div>
                    </div>
                    <div class="lcars-form-row">
                        <div class="lcars-form-field">
                            <label for="phone1"
                                   class="lcars-u-1 uppercase"
                                   title=""
                                   style="margin-right: 10px;">
                                <b>{{ form.phone1.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="phone1"
                                   name="phone1"
                                   type="tel"
                                   title=""
                                   value=""
                                   placeholder="Enter the phone number"
                                   maxlength="16"/>
                        </div>
                        <div class="lcars-form-field">
                            <label for="phone2"
                                   title=""
                                   class="lcars-u-1 uppercase">
                                <b>{{ form.phone2.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="phone2"
                                   name="phone2"
                                   type="tel"
                                   title=""
                                   value=""
                                   placeholder="Enter the phone number"
                                   maxlength="16"/>
                        </div>
                    </div>
                    <div class="lcars-form-row">
                        <div class="lcars-form-field">
                            <label for="whatsapp"
                                   class="lcars-u-1 uppercase"
                                   title=""
                                   style="margin-right: 10px;">
                                <b>{{ form.whatsapp.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="whatsapp"
                                   name="whatsapp"
                                   type="email"
                                   title=""
                                   value=""
                                   placeholder="Enter the whatsapp number"
                                   maxlength="48"/>
                        </div>
                        <div class="lcars-form-field">
                            <label for="twitter"
                                   title=""
                                   class="lcars-u-1 uppercase">
                                <b>{{ form.twitter.label }}</b>
                            </label>
                            <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                                   id="twitter"
                                   name="twitter"
                                   type="text"
                                   title=""
                                   value=""
                                   placeholder="Enter the twitter name"
                                   maxlength="15"/>
                        </div>
                    </div>
                    <div class="lcars-form-row">
                        <div class="lcars-form-field">
                            <label class="lcars-u-1"
                                   title=""
                                   style="margin-right: 10px;">
                                <b>{{ form.department.label }}</b>
                            </label>
                            <select id="add_dep_select"
                                    class="lcars-select more-width lcars-black-bg lcars-golden-tanoi-color"
                                    name="department"
                                    title=""
                                    required>
                                {% for department in department_list %}
                                  <option value="{{ department.pk }}" {% if employee.department.pk == department.pk %}selected{% endif %}>{{ department.name }}</option>
                                {% endfor department_list %}
                            </select>
                        </div>
                    </div>
                    {% include './includes/_form_buttons_employee.html' %}
                </div> <!--  lcars-form -->
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}