users/urls.py
from django.urls import path, re_path

from .views import RegisterView, SigninView, SignoutView, MyPasswordResetView, MyPasswordResetDoneView, \
    MyPasswordResetFromKeyView,MyPasswordResetFromKeyDoneView, MyPasswordChangeView, UserDetailView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', SigninView.as_view(), name='signin'),
    path('logout/', SignoutView.as_view(), name='signout'),
    path('password/change/', MyPasswordChangeView.as_view(), name='password_change'),
    path('password/reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", MyPasswordResetFromKeyView.as_view(),
            name="reset_password_from_key", ),
    path("password/reset/key/done/", MyPasswordResetFromKeyDoneView.as_view(), name="reset_password_from_key_done", ),
    path('user/detail/', UserDetailView.as_view(), name='user_detail'),
    ]

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'users/css/login.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8 lcars-black-bg">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">SIGN IN</div>
        <div class="lcars-u-8-5" style="margin-left: 40px;">
            <form id="signin_form"
                  action="{% url 'users:signin' %}"
                  method="POST">
                {% csrf_token %}
                <p> <!-- Email input -->
                    <label for="login"
                           class="lcars-u-1 uppercase"
                           title="Required. Enter your email you registered with"
                           style="display: inline-block;">
                        <b>Email*: </b>
                    </label>
                    <input class="lcars-u-6 decorated rounded lcars-golden-tanoi-color"
                           id="login" name="login"
                           type="email"
                           title="Required. Enter your email you registered with"
                           placeholder="Enter the owner email address"
                           maxlength="254"
                           required
                           autofocus>
                </p>
                <p>
                <div class="lcars-row">
                    <div class="lcars-u-8">
                        <label for="password"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter your password"
                               style="display: inline-block;">
                            <b>Password*: </b>
                        </label>
                        <input class="lcars-u-6 decorated rounded lcars-golden-tanoi-color"
                               id="password"
                               name="password"
                               type="password"
                               title="Required. Enter your password"
                               placeholder="Enter a password"
                               maxlength="128"
                               required>
                    </div>
                </div>
                </p>
                <p>
                    <a class=""
                       title="Click on this link if you forgot your password"
                       href="{% url 'users:password_reset' %}">Forgot Password?</a>
                </p>
                {% include "./includes/_form_buttons.html" %}
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'users/css/logout.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8 lcars-black-bg">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">SIGN OUT</div>
        <div class="lcars-u-8-3" style="margin-left: 40px;">
            <p>Are you sure you want to sign out?</p>
            <form id="signin_form" action="{% url 'users:signout' %}" method="POST">
                {% csrf_token %}
                {% include "./includes/_form_buttons.html" %}
            </form>

        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'users/css/password_change.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8 lcars-black-bg">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">CHANGE PASSWORD
        </div>
        <div class="lcars-u-8-6" style="margin-left: 40px;">
            <form id='password_change_form'
                  method="POST"
                  action="{% url 'users:password_change' %}">
                {% csrf_token %}
                <br>
                    <div class="lcars-u-4">
                        <label for="oldpassword"
                               title="Required. Enter your old password"
                               class="lcars-u-1 uppercase"
                               style="display: inline-block;">
                            <b>{{ form.oldpassword.label }}</b>
                        </label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               name="oldpassword"
                               title="Required. Enter your old password"
                               type="password"
                               placeholder="Enter the current password"
                               id="oldpassword"
                               maxlength="128"
                               autofocus
                               required>
                    </div>
                    <br>
                    <div class="lcars-u-4">
                        <label for="password1"
                               title="Required. Enter your new password"
                               class="lcars-u-1 uppercase"
                               style="display: inline-block;">
                            <b>{{ form.password1.label }}</b>
                        </label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               name="password1"
                               type="password"
                               title="Required. Enter your new password"
                               placeholder="Enter a password"
                               id="password1"
                               maxlength="128"
                               required>
                    </div>
                    <br>
                    <div class="lcars-u-4" style="display: table;">
                        <label for="password2"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter your new password again"
                               style="display: table-cell;">
                            <b>{{ form.password2.label }}</b>
                        </label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               style="display: table-cell; margin-left:5px;"
                               title="Required. Enter your new password again"
                               name="password2"
                               type="password"
                               id="password2"
                               placeholder="Enter again the  password"
                               maxlength="128"
                               required>
                    </div>
                    {% include "./includes/_form_buttons.html" %}
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">PASSWORD RESET</div>
        <div class="lcars-u-8-4" style="margin-left: 40px;">
            <p>
                <p>Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.</p>
            </p>
            <form id="password_reset_form" action="{% url 'users:password_reset' %}" method="POST">
                {% csrf_token %}
                <p> <!-- Email input -->
                    <label for="email" class="lcars-u-1 uppercase" style="display: inline-block;"><b>Email*: </b></label>
                    <input class="lcars-u-6 decorated rounded lcars-golden-tanoi-color" id="email" name="email" type="email"
                           placeholder="Enter the owner email address"
                           maxlength="254" required autofocus>
                </p>
                <p class="lcars-u-7" style="margin-top:2em">
                    <button class="lcars-element button uppercase" style="width: 8em;margin-left: 50%;" type="submit">Reset Password</button>
                </p>
            </form>
            <p>
                <p>Please contact us if you have any trouble resetting your password.</p>
            </p>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">PASSWORD RESET</div>
        <div class="lcars-u-8-3" style="margin-left: 40px;">
            <p>
                We have sent you an e-mail. If you have not received it please check your spam folder.
            </p>
            <p>
                Otherwise contact us if you do not receive it in a few minutes.
            </p>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/password_reset_from_key.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">{% if token_fail %}BAD TOKEN{% else %}RESET PASSWORD{% endif %}
        </div>
        <div class="lcars-u-8-4" style="margin-left: 40px;">
            {% if token_fail %}
                {% url 'users:password_reset' as passwd_reset_url %}
                <p>The password reset link was invalid, possibly because it has already been used. Please
                    request a <a href="{{ passwd_reset_url }}">new password reset</a>.
                </p>
            {% else %}
            <form id='password_reset_from_key_form' method="POST" action="{{ action_url }}">
                {% csrf_token %}
                    <div class="lcars-u-4">
                        <label for="password1" class="lcars-u-1 uppercase"
                               style="display: inline-block;"><b>{{ form.password1.label }}</b></label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color" name="password1" type="password"
                               placeholder="Enter a password" id="password1"
                               maxlength="128" required>
                    </div>
                    <br>
                    <div class="lcars-u-4" style="display: table;">
                        <label for="password2" class="lcars-u-1 uppercase" style="display: table-cell;"><b>{{ form.password2.label }}</b></label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               style="display: table-cell; margin-left:5px;" name="password2"
                               type="password" id="password2"
                               placeholder="Enter again the  password"
                               maxlength="128" required>
                    </div>
                    <p class="lcars-u-7" style="margin-top:2em">
                        <button class="lcars-element button uppercase" style="width: 8em;margin-left: 50%;" type="submit">Change Password</button>
                    </p>
            </form>
            {% endif %}
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/password_reset_from_key_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">CHANGE PASSWORD</div>
        <div class="lcars-u-8-2" style="margin-left: 40px;">
            <p>Your password is now changed.</p>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>

{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'users/css/register.css' %}">
{% endblock css %}

{% block script %}

{{ block.super }}
<script src="{% static 'js/register.js' %}"></script>

{% endblock script %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8 lcars-black-bg">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">REGISTER</div>
        <div class="lcars-u-8-6" style="margin-left: 40px;">
            <form id="register_form"
                  action="{% url 'users:register' %}"
                  method="POST">
                {% csrf_token %}
                <p> <!-- Email input -->
                    <label for="email"
                           class="lcars-u-1 uppercase"
                           title="Required. Enter the email address of the entity representative"
                           style="display: inline-block;">
                        <b>{{ form.email.label }}</b>
                    </label>
                    <input class="lcars-u-6 decorated rounded lcars-golden-tanoi-color"
                           id="email"
                           name="email"
                           type="email"
                           title="Required. Enter the email address of the entity representative"
                           placeholder="Enter an email address"
                           maxlength="254"
                           required
                           autofocus>
                </p>
                <p> <!-- Entity name input -->
                    <label for="entity"
                           class="lcars-u-1 uppercase"
                           title="Required. Enter the name of the entity"
                           style="display: inline-block;">
                        <b>{{ form.entity.label }}</b>
                    </label>
                    <input class="lcars-u-6 decorated rounded lcars-golden-tanoi-color"
                           id="entity"
                           name="entity"
                           type="text"
                           title="Required. Enter the name of the entity"
                           placeholder="Enter the entity name"
                           maxlength="48"
                           required/>
                </p>
                <p>
                <div class="lcars-row">
                    <div class="lcars-u-4">
                        <label for="first_name"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter the representative first name"
                               style="margin-right: 15px;">
                            <b>{{ form.first_name.label }}</b>
                        </label>
                        <select class="lcars-black-bg lcars-white-color"
                                id="title"
                                name="title"
                                title="Required. Choose a title from the list"
                                required>
                            <option value="1" selected>Mr.</option>
                            <option value="2">Mrs.</option>
                            <option value="3">Ms.</option>
                        </select>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color" id="first_name"
                               style="width: 15.50rem;"
                               name="first_name"
                               type="text"
                               title="Required. Enter the representative first name"
                               placeholder="Enter your first name"
                               maxlength="150"
                               required/>
                    </div>
                    <div class="lcars-u-4">
                        <label for="last_name"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter the representative last name"
                               style="display: inline-block;">
                            <b>{{ form.last_name.label }}</b>
                        </label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               id="last_name"
                               name="last_name"
                               title="Required. Enter the representative last name"
                               type="text"
                               placeholder="Enter the entity name"
                               maxlength="150"
                               required/>
                    </div>
                </div>
                </p>
                <p>
                <div class="lcars-row">
                    <div class="lcars-u-4">
                        <label for="password1"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter a password"
                               style="display: inline-block;">
                            <b>{{ form.password1.label }}</b>
                        </label>
                        <input class="lcars-u-3 half decorated rounded lcars-golden-tanoi-color"
                               name="password1"
                               type="password"
                               title="Required. Enter a password"
                               placeholder="Enter a password"
                               id="password1"
                               maxlength="128"
                               required>
                    </div>
                    <div class="lcars-u-4"
                         style="display: table;">
                        <label for="password2"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter the chosen password again"
                               style="display: table-cell;">
                            <b>{{ form.password2.label }}</b>
                        </label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               style="display: table-cell; margin-left:5px;"
                               name="password2"
                               title="Required. Enter the chosen password again"
                               type="password"
                               id="password2"
                               placeholder="Enter again the  password"
                               maxlength="128"
                               required>
                    </div>
                </div>
                <input id="id_ctrl_flag"
                       type="hidden"
                       value="0"
                       name="ctrl_flag">
                </p>
                <div class="lcars-row centered button-row">
                    <div class="lcars-column lcars-u-2">
                        <div class="button-grid">
                            <button class="lcars-element button uppercase lcars-husk-bg"
                                    type="submit">Transmit
                            </button>
                            <a href="{% url 'home' %}">
                                <button class="lcars-element button uppercase lcars-red-damask-bg"
                                        type="button">Cancel
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>
{% endblock content %}

users/templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'users/css/user_detail.css' %}">
{% endblock css %}

{% block content %}
<div class="lcars-row centered">
    <div class="lcars-bracket left hollow"></div>
    <div class="lcars-column lcars-u-8">
        <div class="lcars-element lcars-u-8" style="height: 2rem;">USER DETAIL</div>
        <div class="lcars-u-8-3" style="margin-left: 40px;">
            <form id="user_detail_form"
                  action="{% url 'users:user_detail' %}"
                  method="POST">
                {% csrf_token %}
                <br>
                <div class="lcars-row">
                    <div class="lcars-u-4">
                        <label for="first_name"
                               class="lcars-u-1 uppercase"
                               title="Required. Enter your title from the list and first name"
                               style="margin-right: 15px;">
                            <b>{{ form.first_name.label }}</b>
                        </label>
                        <select class="lcars-black-bg lcars-white-color"
                                id="title"
                                name="title"
                                title="Required. Choose a title from the list"
                                required>
                            <option value="1" {% if form.title.value == '1' %}selected{% endif %}>Mr.</option>
                            <option value="2" {% if form.title.value == '2' %}selected{% endif %}>Mrs.</option>
                            <option value="3" {% if form.title.value == '3' %}selected{% endif %}>Ms.</option>
                        </select>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               id="first_name"
                               name="first_name"
                               value="{% if form.first_name.initial %}{{ form.first_name.initial }}{% endif %}"
                               type="text"
                               title="Required. Enter your first name"
                               placeholder="Enter your first name"
                               maxlength="150"
                               required
                               autofocus/>
                    </div>
                    <div class="lcars-u-4">
                        <label for="last_name"
                               class="lcars-u-1 uppercase"
                               style="display: inline-block;">
                            <b>{{ form.last_name.label }}</b>
                        </label>
                        <input class="lcars-u-2 decorated rounded lcars-golden-tanoi-color"
                               id="last_name"
                               name="last_name"
                               value="{% if form.last_name.initial %}{{ form.last_name.initial }}{% endif %}"
                               type="text"
                               placeholder="Enter the entity name"
                               maxlength="150"
                               required/>
                    </div>
                </div>
                {% include './includes/_form_buttons.html' %}
            </form>
        </div>
        <div class="lcars-element lcars-u-8" style="height: 0.75rem;"></div>
    </div>
    <div class="lcars-bracket right hollow"></div>
</div>
{% endblock content %}